### ISSUE TITLE
A new format of task runner's configuration file

### ISSUE THREAD

**Issue by alkchr** [colegion/goal#4]
Goal's `run` tool uses YAML for its [configuration file](https://github.com/colegion/goal/blob/master/internal/skeleton/goal.yml). The file is described [here](https://github.com/colegion/goal/blob/gh-pages/manual/run/index.md). However, I'd like to replace it by something else. I want all code including dependencies to meet the following requirements (apart from the general quality of the library):
1. `gofmt`-ed with `-s` flag;
2. `golint`-ed
3. checked with `go vet`.
go-yaml doesn't meet those requirements and that is the only Go implementation of YAML that is active and maintained.

I have played with different formats. Not sure about XML. But JSON doesn't work, comments are not supported and the whole config looks very difficult to read and understand with all those `"`, `,`, and `{}` that could be omitted.
It is also possible to use a custom format. [Here](https://github.com/alkchr/espresso) is one I have developed right for this use-case.

**Comment by DavidHunter** [comment]
I like the idea of this and I think [espresso]( https://github.com/alkchr/espresso) looks nice

**Comment by alkchr** [comment]
@DavidHunter Cool, I'll modify the `run` tool to use it then.

**Comment by DavidHunter** [comment]
The good thing about using YAML is that their is not much effort in using it

**Comment by alkchr** [comment]
Well, I have thought it over and decided it is possible to loosen requirements for dependencies of the toolkit. We are using `fsnotify` that does not meet the requirements but has no alternatives anyway. Moreover, looks like sources of Go's internals do not meet them either.
The skeleton app and its dependencies (i.e. not the toolkit but what it generates) still will have to be `gofmt -s`ed, `go lint`ed, etc.

But changes to the config are still needed. Now the configuration file looks like:
```yaml
watch:
  ./controllers*:            # Watch "./controllers" and its subdirectories.
    - go generate ./...
    - /run buildApp
    - /single startApp

buildApp:
  - go build ./
startApp: ./bin
```
I'd like it to be:
```yaml
watch:
  ./controllers*:
    - run: go generate ./...
    - include: buildApp
    - include: startApp

includes:
  buildApp:
    - run: go build ./
  startApp:
    - single: ./bin
```

**Comment by alkchr** [comment]
I'm working on the task runner now. I have decided to replace go-yaml by [go-gypsy](https://godoc.org/github.com/kylelemons/go-gypsy/yaml). It is not fully compatable with the 1.2 standard but it meets the requirements I've mentioned above.

I'm also thinking about replacement of the current format:
```yaml
init:
  - go build ./
  - /start xxx
  - /single zzz
  - /echo "smth"
xxx:
  - go test ./
zzz: ./bin/run
```
By the following one:
```yaml
init:
  - run: "go build ./"
  - exec: xxx
  - exec: zzz
  - echo: "smth"
cmds:
  xxx:
    - {run: "go test ./", async: true}
  zzz:
    - single: "./bin/run"
```
I.e. YAML syntax is used instead of custom `/cmdName` constructions. @DavidHunter what do you think about the change? IMO it decreases readability of the configuration file (though I expected the opposite).
